#!/bin/sh

# gstopdf - Ghostscript-based PDF filter for CUPS
#
# Note: This is only a wrapper filter, the real work is done by gstoraster
#
# (C) 2012 Till Kamppeter <till.kamppeter@gmail.com>
#
# Released under GPL 2 or later
#

echo "DEBUG: gstopdf argv[$#] = $@" >&2
echo "DEBUG: PPD: $PPD" >&2

if [ $# -lt 5 -o $# -gt 6 ]; then
    echo "ERROR: gstopdf job-id user title copies options [file]" >&2
    exit 1
fi

# Read from given file.
if [ -n "$6" ]; then
    exec <"$6"
fi

OUTFORMAT=PDF $CUPS_SERVERBIN/filter/gstoraster "$1" "$2" "$3" "$4" "$5"
