.TH driverless 1 "27 Dec 2016" "" ""
.SH NAME
\fBdriverless \fP- PPD generator utility for driverless printing
\fB
.SH SYNOPSIS
.nf
.fam C
\fBdriverless\fP [\fB-h\fP | \fB--help\fP | \fB--version\fP] [\fB-d\fP | \fB-v\fP | \fB--debug\fP] [\fBlist\fP] | [\fBcat\fP \fIdriver URI\fP] | [\fIIPP printer URI\fP]

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
\fBdriverless\fP generates PPD files for printers which are designed
for driverless IPP printing (currently IPP Everywhere, AirPrint,
Mopria, and Wi-Fi-Direct printers, network printers and also
IPP-over-USB printers with the help of ippusbxd(8)) by polling
capability information from the printers via IPP. it can be either
called for listing suitable printers in the network and for actually
generating the PPD. It can also be called by CUPS when CUPS is listing
available PPDs/drivers or creating print queues, making the setup of
driverless printers with printer setup tools transparently working.
.P
driverless is placed in /usr/lib/cups/driver/ for listing available
driverless-capable printers and generating PPDs for them. It should
also be put in /usr/lib/cups/backend/ (preferably by a symbolic link)
to list IPP device URIs for suitable printers. Printer setup tools
like system-config-printer, the CUPS web interface at
http://localhost:631/, and CUPS' command line utilities can use
driverless with CUPS to list available driverless-capable printers,
determine their IPP device URIs and generate PPDs for them. The
printers will be automatically and correctly set up for driverless
printing. Note that driverless printing requires IPP communication
with the printer.
.P
A second symbolic link to /usr/lib/cups/driver/driverless from
/usr/bin/ allows driverless to be called directly by a user.
.SH OPTIONS
.TP
.B
\fB-h\fP, \fB--help\fP, \fB--version\fP
Show help page, including version number.
.TP
.B
\fB-v\fP, \fB-d\fP, \fB--debug\fP
Debug mode, verbose logging to stderr.
.TP
.B
\fBlist\fP
List the driver URIs and metadata for all available IPP printers suitable
for driverless PPD file generation (to be used by CUPS).
.TP
.B
\fBcat\fP \fIdriver URI\fP
Generate the PPD file for the supplied \fIdriver URI\fP from the output of "list"
(to be used by CUPS).
.TP
.B
\fIIPP printer URI\fB
Generate the PPD file for the supplied \fIIPP printer URI\fP (suitable URIs are listed when calling driverless without options).
.P
When called without options, the IPP printer URIs of all available
driverless-capable IPP printers will be listed.
.P
.SH SEE ALSO

\fBcups-browsed\fP(8), \fBippfind\fP(1), \fBippusbxd\fP(8)
.PP
.SH AUTHOR
The authors of \fBdriverless\fP are listed in /usr/share/doc/\fBcups-filters\fP/AUTHORS.
.PP
