#!/bin/sh
#
# Note: This is only a wrapper for driverless-fax, the real work is done by
# driverless
#
# (C) 2020 Nidhi Jain
# (C) 2012-2020 Till Kamppeter <till.kamppeter@gmail.com>
#
# Released under GPL 2 or later
#

if [ $# -eq "0" ]; then
    DEVICE_TYPE=FAX /usr/lib/cups/backend/driverless
    elif [ $# -eq "1" ]; then
        DEVICE_TYPE=FAX /usr/lib/cups/driver/driverless "$1"
    elif [ $# -eq "2" ]; then
        DEVICE_TYPE=FAX /usr/lib/cups/driver/driverless "$1" "$2"
    else
        echo "ERROR: Too many arguments"
fi
